import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { Layout } from "@/components/layout";
import Hero from "@/sections/hero";
import Intro from "@/sections/Intro";
import About from "@/sections/About";
import CTA from "@/sections/CTA";

export default function Home() {

  return (
    <>
      <Head>
        <title>Landing Page Client</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Layout>
        <Hero />
        <div className="relative z-10 bg-white">
          <Intro />
          <About />
        </div>
        <CTA />
      </Layout>
    </>
  );
}

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}
